"on":
  - push
name: Test
jobs:
  readmeExamples:
    name: "[TEST] README examples"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: npm ci
      - run: npm run build
      - name: README example
        uses: ./
        id: audit
        env:
          APP_ID: ${{ secrets.OPENCONTOSO_APP_ID }}
          PRIVATE_KEY: ${{ secrets.OPENCONTOSO_PRIVATE_KEY }}
      - run: |
          echo '${{ steps.audit.outputs.repositories }}'
